name: norminette

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
    - name: Norminette
      continue-on-error: true
      run: |
        pip3 install Norminette
        norminette libft srcs/*.c incs/*.h
        norminette --version
